version: '3.8'

services:
  pgadmin:
    build: docker/pgadmin
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - telbit-net
    env_file:
      - .env
  postgres:
    build: docker/postgres
    volumes:
      - ./docker/postgres/data:${PGDATA}
    hostname: postgres
    ports:
      - 5433:5432
    expose:
      - 5433
    networks:
      - telbit-net
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telbit"]
      interval: 10s
      timeout: 5s
      retries: 5
  telbit:
    build:
      dockerfile: ./docker/telbit/Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - telbit-net
    env_file:
      - .env

networks:
  telbit-net:
