export const ADD_COST = 'ADD_COST_SCENE';
export const ADD_CATEGORY = 'ADD_CATEGORY_SCENE';
export const CONFIRM = 'CONFIRM_SCENE';

export const CHANGE_COST = 'CHANGE_COST_SCENE';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT_SCENE';
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT_SCENE';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY_SCENE';
export const CHANGE_MONTH = 'CHANGE_MONTH_SCENE';

export const CANCEL = 'CANCEL_SCENE';